
const LOADING = "[AUTH] LOADING";
const TOKEN = "[AUTH] TOKEN";
const REHYDARATE = "[AUTH] REHYDARATE";
const STOREID = "[AUTH] STOREID";

export {
    LOADING,
    TOKEN,
    REHYDARATE,
    STOREID
}